name:                haskell-aes
version:             0.1.0.0
github:              "githubuser/haskell-aes"
license:             BSD3
author:              "Tom Busby"
maintainer:          "tom@busby.ninja"
copyright:           "2018 Tom Busby"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-aes#readme>

dependencies:
- base >= 4.7 && < 5
- split
- bytestring

library:
  source-dirs: src

executables:
  haskell-aes-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-aes

tests:
  haskell-aes-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-aes
    - hspec
    - QuickCheck
